config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index'
  get '/tasks/new', to: 'tasks#new', as: :new
  get '/tasks/:id', to: 'tasks#show', as: :task

  post '/tasks', to: 'tasks#create'

  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch '/tasks/:id', to: 'tasks#update'

  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  scope :completed, -> {
    where(:completed => true)
  }

  scope :todo, -> {
    where(:completed => false)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'icon2.png' %>
    <title>Task Manager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/c12cfd8662.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "shared/leftbar"%>
    <%= yield %>
  </body>
</html>

app/views/shared/_leftbar.html.erb
<div class="title-container">
  <div class="header">
    <h1> Task Manager </h1>
  </div>
</div>

<div class="task-manager">
  <div class="left-bar">
      <button class="btn create-button">
        <%= link_to "+ Add new task", new_path%>
      </button>
    <div class="left-content">
    </div>
  </div>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="btn">
      <button type="button"  onclick="window.location.href = '/tasks';">
        <i class="fas fa-arrow-left"></i>
        Back
      </button>
    </div>
  </div>

<div class="card m-3">
  <div class="card-body">
    <h1> New tasks </h1>
    <%= form_for(@task) do |f| %>

     <div>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :details %>
        <%= f.text_field :details, class: 'form-control' %>
      </div>

      <div>
        <%= f.check_box('completed') %>
        <span>Completed</span>
      </div>

      <%= f.submit value = "Update task", class: 'btn-flat', data: { disable_with: "Task has been updated" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">

    <div class="col-sm">
      <h2>To-Do</h2>
      <ul>
        <% @tasks.todo.each do |task| %>
        <li>
          <i class="far fa-square"></i>
          <%= task.title%>
          <button class="btn">
            <%= link_to '<i class="far fa-edit"></i>'.html_safe, task_path(task["id"]) %>
          </button>

           <button class="btn">
             <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, task_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
           </button>
        </li>
        <% end %>
      </ul>
    </div>

    <div class="col-sm">
      <h2>Completed</h2>
      <ul>
        <% @tasks.completed.each do |task| %>
        <li>
          <% if task.completed == true %>
            <i class="far fa-check-square"></i>
            <%= task.title%>
          <button class="btn">
             <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, task_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
           </button>
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>


  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="btn">
      <button type="button"  onclick="window.location.href = '/tasks';">
        <i class="fas fa-arrow-left"></i>
        Back
      </button>
    </div>
  </div>

<div class="card m-3">
  <div class="card-body">
    <h1> New tasks </h1>
    <%= form_for(@task) do |f| %>
    <div>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :details %>
        <%= f.text_field :details, class: 'form-control' %>
      </div>

      <%= f.submit value = "Create a task", class: 'btn-flat' %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row">
    <div class="btn">
      <button type="button"  onclick="window.location.href = '/tasks';">
        <i class="fas fa-arrow-left"></i>
        Back
      </button>
    </div>
  </div>

<div class="card m-3">
  <div class="card-body">
    <h1><%= @task.title %></h1>
    <p class = 'details'> <%= @task.details %> </p>

      <% if @task.completed == true %>
        <i class="far fa-check-square"></i> This task is completed
      <% else %>
        <i class="far fa-square"></i> This task is not completed
      <% end %>

      <div class="edit">
        <%= link_to 'Edit task', edit_path, class: 'btn-flat' %>
      </div>
    </div>
  </div>
</div>